# Generated by Django 3.0.14 on 2022-12-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbCadastroVacinaAplicada',
            fields=[
                ('idvacina', models.AutoField(db_column='idVacina', primary_key=True, serialize=False)),
                ('nome_vacina_aplicada', models.CharField(max_length=45)),
                ('data_vacina_aplicada', models.DateField(db_column='data_vacina aplicada')),
                ('local_vacina_ok', models.CharField(max_length=45)),
                ('lote_vacina_ok', models.CharField(blank=True, db_column='Lote_vacina_ok', max_length=45, null=True)),
            ],
            options={
                'db_table': 'tb_cadastro_vacina_aplicada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbCalendarioVacina',
            fields=[
                ('id_vacina', models.AutoField(primary_key=True, serialize=False)),
                ('cod_vacina', models.CharField(max_length=8)),
                ('descricao_vacina', models.CharField(max_length=45)),
                ('observacao', models.CharField(max_length=45)),
                ('meses', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_calendario_vacina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbLoginUsuario',
            fields=[
                ('id_log_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('user_name_login', models.CharField(max_length=45)),
                ('user_password', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tb_login_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbMunicipioBrasil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge7', models.IntegerField(blank=True, db_column='IBGE7', null=True)),
                ('uf', models.TextField(blank=True, db_column='UF', null=True)),
                ('município', models.TextField(blank=True, db_column='Município', null=True)),
                ('região', models.TextField(blank=True, db_column='Região', null=True)),
                ('população_2010', models.IntegerField(blank=True, db_column='População 2010', null=True)),
            ],
            options={
                'db_table': 'tb_municipio_brasil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbMunicipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge7', models.IntegerField(blank=True, db_column='IBGE7', null=True)),
                ('uf', models.TextField(blank=True, db_column='UF', null=True)),
                ('município', models.TextField(blank=True, db_column='Município', null=True)),
                ('região', models.TextField(blank=True, db_column='Região', null=True)),
                ('população_2010', models.IntegerField(blank=True, db_column='População 2010', null=True)),
            ],
            options={
                'db_table': 'tb_municipios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbUbsDadosBrasil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnes', models.TextField(db_column='CNES')),
                ('uf', models.IntegerField(blank=True, db_column='UF', null=True)),
                ('ibge', models.IntegerField(blank=True, db_column='IBGE', null=True)),
                ('nome', models.TextField(blank=True, db_column='NOME', null=True)),
                ('logradouro', models.TextField(blank=True, db_column='LOGRADOURO', null=True)),
                ('bairro', models.TextField(blank=True, db_column='BAIRRO', null=True)),
                ('latitude', models.TextField(blank=True, db_column='LATITUDE', null=True)),
                ('longitude', models.TextField(blank=True, db_column='LONGITUDE', null=True)),
            ],
            options={
                'db_table': 'tb_ubs_dados_brasil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbUbsDadosSp',
            fields=[
                ('codigoubs', models.IntegerField(db_column='codigoUBS', primary_key=True, serialize=False)),
                ('codigonacionalsaude', models.IntegerField(db_column='codigoNacionalSaude')),
                ('endereçoubs', models.TextField(db_column='endereçoUBS')),
                ('numeroenderecoubs', models.CharField(db_column='numeroEnderecoUBS', max_length=10)),
                ('cepubs', models.CharField(db_column='cepUBS', max_length=10)),
                ('bairroenderecoubs', models.CharField(db_column='bairroEnderecoUBS', max_length=45)),
                ('horariofuncionamentoubs', models.CharField(db_column='horarioFuncionamentoUBS', max_length=45)),
                ('tipoprimeironivelubs', models.CharField(blank=True, db_column='tipoPrimeiroNivelUBS', max_length=45, null=True)),
                ('tiposegundonivelubs', models.CharField(blank=True, db_column='tipoSegundoNivelUBS', max_length=45, null=True)),
                ('nometipoprimeironivel', models.CharField(blank=True, db_column='nomeTipoPrimeiroNivel', max_length=45, null=True)),
                ('telefone1ubs', models.CharField(blank=True, db_column='telefone1UBS', max_length=45, null=True)),
                ('telefone2ubs', models.CharField(blank=True, db_column='telefone2UBS', max_length=45, null=True)),
                ('exibirreferenciaubs', models.CharField(blank=True, db_column='exibirReferenciaUBS', max_length=45, null=True)),
                ('informacoesidentificacaoubs', models.TextField(blank=True, db_column='informacoesIdentificacaoUBS', null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tb_ubs_dados_sp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VacinaProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vacina_profile',
                'managed': False,
            },
        ),
    ]
