# Generated by Django 3.0.14 on 2022-12-18 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='TbCadastroVacinaAplicada',
        ),
        migrations.DeleteModel(
            name='TbCalendarioVacina',
        ),
        migrations.DeleteModel(
            name='TbLoginUsuario',
        ),
        migrations.DeleteModel(
            name='TbMunicipioBrasil',
        ),
        migrations.DeleteModel(
            name='TbMunicipios',
        ),
        migrations.DeleteModel(
            name='TbUbsDadosBrasil',
        ),
        migrations.DeleteModel(
            name='TbUbsDadosSp',
        ),
        migrations.DeleteModel(
            name='VacinaProfile',
        ),
    ]
